export {default as Loader} from './Loader'
export {default as Footer} from './Footer'
export {default as NavBar} from './Navbar'
export {default as Welcome} from './Welcome'
export {default as Services} from './Services'
export {default as RePaper} from './RePaper'
export {default as ContactForm} from './ContactForm'